package com.libreuml.backend.domain.model;

public enum AuditEventType {
    USER_REGISTERED,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_ACCOUNT_DELETED,
    OAUTH_LOGIN,
    OAUTH_UNLINKED,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    MODEL_UPDATED,
    DIAGRAM_CREATED,
    DIAGRAM_UPDATED,
    DIAGRAM_DELETED
}
